#string pratice
# print("My Name is" + " 2")
# print("My Name is " * 2)
# print("------------------------")
# ab = ("i am at pune now.")
# print(ab[3])
# print(ab[9])
# print("------------------------")
# cd = ("2328")
# print(cd[3])
# print("------------------------")
# xy = ("Computer")
# print(xy[-2])

# print("------- Print more char parallelly ----------------")
# kp = ("panther")
# print (kp[3:-1])
# print (kp[3:6])
# print("------- Print more char parallelly ----------------")
# print(kp[:-5])
# print(kp[:5])
# print(kp[20:])
# print("------- Print more char parallelly ----------------")
# print(kp[:20])
# print(kp[:])
# print("------- Print more char parallelly ----------------")
# print(kp[:3] + kp[5:])
# print("------- Print more char parallelly ----------------")

print("Praveen"[7::-1])